'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'
'     Zmiany w tym pliku mogą być przyczyną niepoprawnego zachowania i zostaną utracone w przypadku
'     ponownego wygenerowania kodu. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site_Mobile

    '''<summary>
    '''Kontrolka Head1.
    '''</summary>
    '''<remarks>
    '''Pole generowane automatycznie.
    '''Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''Kontrolka HeadContent.
    '''</summary>
    '''<remarks>
    '''Pole generowane automatycznie.
    '''Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Kontrolka form1.
    '''</summary>
    '''<remarks>
    '''Pole generowane automatycznie.
    '''Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Kontrolka FeaturedContent.
    '''</summary>
    '''<remarks>
    '''Pole generowane automatycznie.
    '''Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
    '''</remarks>
    Protected WithEvents FeaturedContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Kontrolka MainContent.
    '''</summary>
    '''<remarks>
    '''Pole generowane automatycznie.
    '''Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Kontrolka ViewSwitcher1.
    '''</summary>
    '''<remarks>
    '''Pole generowane automatycznie.
    '''Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
    '''</remarks>
    Protected WithEvents ViewSwitcher1 As Global.System.Web.UI.UserControl
End Class
