'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'
'     Zmiany w tym pliku mogą być przyczyną niepoprawnego zachowania i zostaną utracone w przypadku
'     ponownego wygenerowania kodu. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster

    '''<summary>
    '''Kontrolka MainContent.
    '''</summary>
    '''<remarks>
    '''Pole generowane automatycznie.
    '''Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
